name: ci 

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        build:
        - pinned
        - stable
        - beta
        - nightly
        - macos
        - win-msvc
        - win-gnu

        include:
        - build: pinned
          os: ubuntu-latest
          rust: 1.50.0
        - build: stable
          os: ubuntu-latest
          rust: stable
        - build: beta
          os: ubuntu-latest
          rust: beta
        - build: nightly
          os: ubuntu-latest
          rust: nightly
        - build: macos
          os: macos-latest
          rust: nightly
        - build: win-msvc
          os: windows-latest
          rust: nightly
        - build: win-gnu
          os: windows-2019
          rust: nightly-x86_64-gnu

    steps:
    - name: Checkout reopository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
